### PR TITLE
Support custom transport in vegur_proxy

### PR DESCRIPTION
**Pull request by pauldub**
This lets caller of `backend_connection` specify ranch transport to
use instead of `ranch_tcp`, this allows to proxy requests to HTTPS
backends as mentionned in issue #174 

I am not familiar with the contribution process for this repository, so I hope this is sufficient.

### CODE REVIEW

**Comment by pauldub** [comment]
Hi, I have implemented the changes suggested by @ferd and did my best to update type specifications.

**Comment by ferd** [comment]
The contribution instructions are rather brief but nevertheless documented at https://github.com/heroku/vegur#contributing -- namely the need for tests and documentation, tests being the most critical ones missing in here.

At a glance this seems to be fine, but I'd say a test that runs the full integration would be ideal. You can see the `vegur_roundtrip_SUITE` module for tests, and make some SSL version based on the [current init function](https://github.com/heroku/vegur/blob/master/test/vegur_roundtrip_SUITE.erl#L162-L194) that starts a TCP backend server that is hooked with the rest of tests.

**Comment by pauldub** [comment]
Oh, I did not see that section... I was looking for a document at the root of the repository. I will write related tests within a few days.

**Comment by pauldub** [comment]
I adapted the `vegur_roundtrip_SUITE` to use a SSL backend, all but 2 tests are green but I have a hard time finding what is wrong with them. I am also concerned about duplicating such a large test suite, is there a better way to run the existing suite against an SSL backend? Most changes are related to using `ssl` rather than `gen_tcp` to communicate with the backend server.

**Comment by pauldub** [comment]
Hi @bt, I did not work on this since my last message. You can look at the failing tests, but I have no idea if @ypaq or @joedevivo have any interest in merging this.

**Comment by ypaq** [comment]
This would need some work. Please group the tests appropriately, no copy&paste to new file. The tests have to pass.

**Comment by pauldub** [comment]
@ypaq thank you for your comment, I'll try and do that. I have to admit that I thought that implementing the rountrip test suit with SSL enabled would have been a good approach given the changes required to add support for custom transport.

**Pull request closed without merging**
